org: sergiohidalgocaceres
app: cursosdev

service: appointment-v6

provider:
  name: aws
  runtime: nodejs24.x
  architecture: x86_64
  stage: ${opt:stage, "dev"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref Topic
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - !GetAtt SQSAppointmentPE.Arn
            - !GetAtt SQSAppointmentCO.Arn
            - !GetAtt SQSAppointmentCL.Arn

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

functions:
  create-appointment:
    handler: src/features/appointment/index.create
    environment:
      TOPIC_ARN: !Ref Topic
    events:
      - http:
          path: /appointment
          method: post

  appointment-enrichment-pe:
    handler: src/features/appointment-enrichment-pe/index.enrichment
    environment:
      SQS_URL: !Ref SQSAppointmentPE
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentEnrichmentPE.Arn

  appointment-pe:
    handler: src/features/appointment-pe/index.create
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentPE.Arn

  appointment-enrichment-cl:
    handler: src/features/appointment-enrichment-cl/index.enrichment
    environment:
      SQS_URL: !Ref SQSAppointmentCL
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentEnrichmentCL.Arn

  appointment-cl:
    handler: src/features/appointment-cl/index.create
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentCL.Arn

  appointment-enrichment-co:
    handler: src/features/appointment-enrichment-co/index.enrichment
    environment:
      SQS_URL: !Ref SQSAppointmentCO
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentEnrichmentCO.Arn

  appointment-co:
    handler: src/features/appointment-co/index.create
    events:
      - sqs:
          arn: !GetAtt SQSAppointmentCO.Arn

resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: topic-appointment

    SNSTopicPESubcription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt SQSAppointmentEnrichmentPE.Arn
        TopicArn:
          Ref: Topic
        RawMessageDelivery: true
        FilterPolicy:
          countryISO:
            - PE
        FilterPolicyScope: MessageBody

    SNSTopicCOSubcription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt SQSAppointmentEnrichmentCO.Arn
        TopicArn:
          Ref: Topic
        RawMessageDelivery: true
        FilterPolicy:
          countryISO:
            - CO
        FilterPolicyScope: MessageBody

    SNSTopicCLSubcription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt SQSAppointmentEnrichmentCL.Arn
        TopicArn:
          Ref: Topic
        RawMessageDelivery: true
        FilterPolicy:
          countryISO:
            - CL
        FilterPolicyScope: MessageBody

    SQSAppointmentPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-pe

    SQSAppointmentCO:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-co

    SQSAppointmentCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-cl

    SQSAppointmentEnrichmentPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-enrichment-pe

    PolicySQSAppointmentEnrichmentPE:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSAppointmentEnrichmentPE
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Resource: !GetAtt SQSAppointmentEnrichmentPE.Arn
              Action: sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref Topic

    SQSAppointmentEnrichmentCO:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-enrichment-co

    PolicySQSAppointmentEnrichmentCO:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSAppointmentEnrichmentCO
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Resource: !GetAtt SQSAppointmentEnrichmentCO.Arn
              Action: sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref Topic

    SQSAppointmentEnrichmentCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-appointment-enrichment-cl

    PolicySQSAppointmentEnrichmentCL:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSAppointmentEnrichmentCL
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Resource: !GetAtt SQSAppointmentEnrichmentCL.Arn
              Action: sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref Topic
