org: sergiohidalgocaceres
app: cursosdev

service: v2

provider:
  name: aws
  runtime: nodejs24.x
  architecture: x86_64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "arn:aws:lambda:*:*:function:*"

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

functions:
  create-appointment:
    handler: src/features/appointment/index.create
    environment:
      LAMBDA_NAME_PE: !Ref AppointmentDashpeLambdaFunction
      LAMBDA_NAME_CL: !Ref AppointmentDashclLambdaFunction
      LAMBDA_NAME_CO: !Ref AppointmentDashcoLambdaFunction
      # LAMBDA_NAME_MX: !Ref AppointmentDashmxLambdaFunction

  appointment-pe:
    handler: src/features/appointment-pe/index.create

  appointment-cl:
    handler: src/features/appointment-cl/index.create

  appointment-co:
    handler: src/features/appointment-co/index.create

  # appointment-mx:
  #   handler: src/features/appointment-mx/index.create

# resources:
#   Resources:
#     AppointmentEC:
#       Type: AWS::Lambda::Function
#       Properties:
#         Runtime: nodejs24.x
#         Handler: index.handler
#         Code:
#           ZipFile: |
#             exports.handler = async function(event) {
#               console.log("Received event EC:", JSON.stringify(event, null, 2));
#             };
#         TracingConfig:
#           Mode: Active
#         Role: arn:aws:iam::282865065290:role/service-role/aws01-lambda-insert-role-5twq9qa3

#     AppointmentPA:
#       Type: AWS::Lambda::Function
#       Properties:
#         Runtime: nodejs24.x
#         Handler: index.handler
#         Code:
#           ZipFile: |
#             exports.handler = async function(event) {
#               console.log("Received event PA:", JSON.stringify(event, null, 2));
#             };
#         TracingConfig:
#           Mode: Active
#         Environment:
#           Variables:
#             LAMBDA_NAME_EC: !Ref AppointmentEC
#         Role: arn:aws:iam::282865065290:role/service-role/aws01-lambda-insert-role-5twq9qa3
